// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEQ5kjiu1WiD0JF7qr56g2sCgY_Sq7lm0',
    appId: '1:584858405851:web:4a28c2586b70f2aa9175fe',
    messagingSenderId: '584858405851',
    projectId: 'app-pass-bbdd7',
    authDomain: 'app-pass-bbdd7.firebaseapp.com',
    storageBucket: 'app-pass-bbdd7.appspot.com',
    measurementId: 'G-0SYF7XRCDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtPGuVP26LaJH7VVlItAqYM01xv65I11c',
    appId: '1:584858405851:android:70e54faa250e461b9175fe',
    messagingSenderId: '584858405851',
    projectId: 'app-pass-bbdd7',
    storageBucket: 'app-pass-bbdd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAthUSFKCeDOyv9Ga-XwQ4dbLdjrm12f6I',
    appId: '1:584858405851:ios:80dca7c26224094b9175fe',
    messagingSenderId: '584858405851',
    projectId: 'app-pass-bbdd7',
    storageBucket: 'app-pass-bbdd7.appspot.com',
    iosBundleId: 'com.example.appPass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAthUSFKCeDOyv9Ga-XwQ4dbLdjrm12f6I',
    appId: '1:584858405851:ios:80dca7c26224094b9175fe',
    messagingSenderId: '584858405851',
    projectId: 'app-pass-bbdd7',
    storageBucket: 'app-pass-bbdd7.appspot.com',
    iosBundleId: 'com.example.appPass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEQ5kjiu1WiD0JF7qr56g2sCgY_Sq7lm0',
    appId: '1:584858405851:web:5c4a717c2d3896ce9175fe',
    messagingSenderId: '584858405851',
    projectId: 'app-pass-bbdd7',
    authDomain: 'app-pass-bbdd7.firebaseapp.com',
    storageBucket: 'app-pass-bbdd7.appspot.com',
    measurementId: 'G-KV342HHG4P',
  );
}
